server:
  port: 8081
  servlet:
    context-path: /api
  error:
      include-message: always
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    #propiedades hibernate
    spring.jpa.hibernate.ddl-auto: update
  h2:
    console.path: /h2-console
    console.settings.trace: false
    console.enabled: true
    spring.h2.console.settings.web-allow-others: false
  liquibase:
    enabled: true
    change-log: classpath:db.changelog.xml
    contexts: ${spring.profiles.active}